services:
  mongo:
    image: mongo:7.0
    container_name: skeleton_mern_rest-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE:-skeleton}
      # auth for admin/root
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-admin}
    restart: always

  backend:
    build: ./backend
    container_name: skeleton_mern_rest-backend
    ports:
      - ${BACKEND_PORT:-5000}:${BACKEND_PORT:-5000}
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - BACKEND_PORT=${BACKEND_PORT:-5000}
      - MONGODB_URI=${MONGODB_URI:-mongodb://dev:dev@mongo:27017/skeleton}
      - TZ=Africa/Tunis
    volumes:
      - ./backend:/usr/src/app
      # Named volume or Anonymous volume, 
      # container-specific directories to avoid conflicts with the host system.
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: skeleton_mern_rest-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL:-http://localhost:3000}
      - NEXT_PUBLIC_BASE_PATH=${NEXT_PUBLIC_BASE_PATH:-}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://backend:5000/api/v1}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
